# Site

title: Maps in R
baseurl: /maps-in-R-lesson
email: cyberhelp@sesync.org
description: ""
# styleurl: https://cdn.rawgit.com/sesync-ci/lesson-stylesheets/1.0.0
styleurl: https://rawgit.com/sesync-ci/lesson-stylesheets/master
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.3.0
lesson: 7

# Slides

slide_sorter:
  - title
  - intro
  - shapefile
  - basicplot
  - raster
  - projections
  - mask
  - tmap
  - leaflet
  - shinyleaflet


# Jekyll

markdown: kramdown
kramdown:
  toc_levels: 2..2
collections:
  - slides
exclude:
  - README.md
  - build.R
  - "*.Rproj"
  - "*.Rmd"
